window.__LT2_BOOT_OK__=true;
const cv=game,ctx=cv.getContext('2d');const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const ships=[{name:'CRIMSON FALCON',stats:[7,7,5,7]},{name:'NOVA SPEAR',stats:[5,6,9,8]},{name:'ECLIPSE RAY',stats:[9,8,4,5]}];
const stgNames=['Night City','Sea Front','Desert Base','Cloudline','Orbital Lift','Deep Space'];
const set=JSON.parse(localStorage.getItem('as_settings')||'{"sens":1.1,"shake":true,"flash":true}');
const G={scene:'title',score:0,stage:1,ship:0,wpn:0,life:3,bomb:3,mult:1,time:0,player:null,en:[],bul:[],eb:[],boss:null,mode:'idle',last:0,input:{id:null,sx:0,sy:0,px:0,py:0,drag:false},fx:[],bg:[],paused:false};
function rs(){let d=Math.min(devicePixelRatio||1,2);cv.width=innerWidth*d;cv.height=innerHeight*d;cv.style.width=innerWidth+'px';cv.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',rs);rs();
function show(id){for(const n of ['title','menu','hangar','stages','settings','tutorial','result']) document.getElementById(n).classList.remove('show'); if(id)document.getElementById(id).classList.add('show'); hud.classList.toggle('show',id===null);}
function bootUI(){sens.value=set.sens;shake.checked=set.shake;flash.checked=set.flash;shipList.innerHTML=ships.map((s,i)=>`<button class='btn' data-i='${i}'>${s.name} SPD${s.stats[0]} FP${s.stats[1]} RNG${s.stats[2]} DUR${s.stats[3]}</button>`).join('');stageList.innerHTML=stgNames.map((s,i)=>`<button class='btn' data-s='${i+1}'>Stage ${i+1}: ${s}</button>`).join('');
 toMenu.onclick=()=>show('menu');startBtn.onclick=()=>startMission(G.stage);hangarBtn.onclick=()=>show('hangar');stageBtn.onclick=()=>show('stages');settingBtn.onclick=()=>show('settings');tutorialBtn.onclick=()=>show('tutorial');
 hangarBack.onclick=()=>show('menu');stageBack.onclick=()=>show('menu');settingsBack.onclick=()=>{saveSet();show('menu')};tutorialBack.onclick=()=>show('menu');resultMenu.onclick=()=>show('menu');pauseBtn.onclick=()=>G.paused=!G.paused;
 shipList.onclick=e=>{if(e.target.dataset.i){G.ship=+e.target.dataset.i;}};stageList.onclick=e=>{if(e.target.dataset.s){startMission(+e.target.dataset.s);}};
 [wpnBtn,skillBtn,bombBtn].forEach(b=>b.addEventListener('pointerdown',ev=>{ev.preventDefault();}));wpnBtn.onclick=()=>G.wpn=(G.wpn+1)%3;skillBtn.onclick=()=>skill();bombBtn.onclick=()=>bombAct();
}
function saveSet(){set.sens=parseFloat(sens.value);set.shake=shake.checked;set.flash=flash.checked;localStorage.setItem('as_settings',JSON.stringify(set));}
function startMission(s){G.scene='game';show(null);Object.assign(G,{score:0,stage:s,life:3,bomb:3,mult:1,time:0,en:[],bul:[],eb:[],boss:null,paused:false});G.player={x:innerWidth/2,y:innerHeight*.82,hp:100,sh:60,sk:0,r:10};mkbg();spawnWave();sync();}
function mkbg(){G.bg=Array.from({length:140},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,z:Math.random()*3+1}))}
function spawnWave(){if(G.stage%4===0){G.mode='warning';G.boss={name:['IRON MAW','HELIOS CORE','TWIN SERPENT','OBLIVION CROWN'][(G.stage/4-1)%4],x:innerWidth/2,y:100,hp:1800,max:1800,ph:1,cd:40,warn:120};return;}G.mode='run';for(let i=0;i<10;i++)G.en.push({k:i%6,x:60+(i*80)%Math.max(120,innerWidth-120),y:-60-i*56,hp:40+(i%3)*30,a:Math.random()*6.28,cd:40});}
function fire(dt){let p=G.player;if(!p)return;p.cd=(p.cd||0)-dt*60;if(p.cd>0)return;p.cd=G.wpn===0?4:G.wpn===1?7:9;if(G.wpn===0)for(let i=-1;i<=1;i++)G.bul.push({x:p.x+i*4,y:p.y-18,vx:i*.4,vy:-13,d:8,c:'#8ff'});if(G.wpn===1)[-3,-1,1,3].forEach(v=>G.bul.push({x:p.x,y:p.y-20,vx:v,vy:-10,d:7,c:'#9f8'}));if(G.wpn===2)[-6,6].forEach(v=>G.bul.push({x:p.x+v,y:p.y-16,vx:0,vy:-18,d:16,c:'#f8f'}));}
function skill(){let p=G.player;if(!p||p.sk<100)return;p.sk=0;for(let i=0;i<48;i++){let a=i/48*Math.PI*2;G.bul.push({x:p.x,y:p.y,vx:Math.cos(a)*7,vy:Math.sin(a)*7,d:13,c:'#fff'});} }
function bombAct(){if(G.bomb<=0)return;G.bomb--;G.eb=[];G.en.forEach(e=>e.hp-=170);if(G.boss)G.boss.hp-=250;}
function update(dt){if(G.paused||G.scene!=='game')return;G.time+=dt;let p=G.player;fire(dt);p.sk=clamp(p.sk+dt*4,0,100);G.bg.forEach(s=>{s.y+=s.z*(1+G.stage*.06);if(s.y>innerHeight){s.y=0;s.x=Math.random()*innerWidth}});
for(const e of G.en){e.y+=1.6+(e.k===0?1.4:0);e.a+=dt*2;if(e.k===1)e.x+=Math.sin(e.a)*2.3;if(e.k===2)e.x+=Math.cos(e.a)*2.8;e.cd-=dt*60;if(e.cd<0){e.cd=e.k===4?24:52;G.eb.push({x:e.x,y:e.y,vx:(Math.random()*2-1)*(e.k===5?2.6:1.2),vy:3.2,r:4,c:['#0ff','#ffb300','#ff5','#f66','#9cf','#f0f'][e.k]});}}
if(G.boss){let b=G.boss;b.warn=Math.max(0,b.warn-dt*60);if(b.warn===0)G.mode='run';b.x=innerWidth/2+Math.sin(G.time*1.1)*190;b.ph=b.hp<b.max*.33?3:b.hp<b.max*.66?2:1;b.cd-=dt*60;if(b.cd<0){if(b.ph===1){b.cd=14;for(let i=0;i<18;i++){let a=i*Math.PI*2/18+G.time;G.eb.push({x:b.x,y:b.y,vx:Math.cos(a)*2.4,vy:Math.sin(a)*2.4+1.4,r:4,c:'#ff7f7f'});}}if(b.ph===2){b.cd=10;let dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy)||1;G.eb.push({x:b.x,y:b.y,vx:dx/d*4.5,vy:dy/d*4.5,r:5,c:'#ffd166'});}if(b.ph===3){b.cd=8;for(let k=-2;k<=2;k++)G.eb.push({x:b.x+k*24,y:b.y,vx:0,vy:5.8,r:5,c:'#00e5ff'});}}}
G.bul.forEach(b=>{b.x+=b.vx*dt*60;b.y+=b.vy*dt*60});G.eb.forEach(b=>{b.x+=b.vx*dt*60;b.y+=b.vy*dt*60});
for(const b of G.bul){for(const e of G.en){if((b.x-e.x)**2+(b.y-e.y)**2<260){b.h=1;e.hp-=b.d;if(e.hp<=0){e.d=1;G.score+=120*G.mult;p.sk=clamp(p.sk+5,0,100)}}}if(G.boss&&((b.x-G.boss.x)**2+(b.y-G.boss.y)**2<5000)){b.h=1;G.boss.hp-=b.d;}}
for(const eb of G.eb){let d2=(eb.x-p.x)**2+(eb.y-p.y)**2;if(d2<250){eb.h=1;if(p.sh>0)p.sh=Math.max(0,p.sh-10);else p.hp-=10;}else if(d2<1200){p.sk=clamp(p.sk+dt*15,0,100);}}
if(p.hp<=0){G.life--;if(G.life<0)return gameOver();p.hp=100;p.sh=60;p.x=innerWidth/2;p.y=innerHeight*.82;}
G.en=G.en.filter(e=>!e.d&&e.y<innerHeight+80);G.bul=G.bul.filter(b=>!b.h&&b.y>-20);G.eb=G.eb.filter(b=>!b.h&&b.y<innerHeight+30&&b.x>-30&&b.x<innerWidth+30);
if(G.boss&&G.boss.hp<=0){G.score+=5000;G.boss=null;stageClear();} if(!G.boss&&G.en.length===0&&G.mode==='run'){G.stage++;spawnWave();}
sync();}
function stageClear(){G.mode='clear';setTimeout(()=>{if(G.stage>=6){result();}else{G.stage++;spawnWave();}},900)}
function result(){G.scene='result';show('result');let rank=G.score>30000?'S':G.score>20000?'A':G.score>12000?'B':'C';resultText.textContent=`Score ${Math.floor(G.score)} / Time ${G.time.toFixed(1)}s / Rank ${rank}`;}
function gameOver(){G.scene='result';show('result');resultText.textContent=`MISSION FAILED Score ${Math.floor(G.score)}`;}
function draw(){const palettes=[['#09182a','#123354','#040a14'],['#09233a','#0d4a66','#032130'],['#2a1c08','#5a3d17','#140a04'],['#1a2647','#3f649b','#0b1122'],['#242447','#5638a3','#101023'],['#030408','#101a39','#04040b']];const p=palettes[(G.stage-1)%palettes.length];const g=ctx.createLinearGradient(0,0,0,innerHeight);g.addColorStop(0,p[0]);g.addColorStop(.5,p[1]);g.addColorStop(1,p[2]);ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);for(const s of G.bg){ctx.fillStyle=`rgba(140,220,255,${0.2+s.z*.2})`;ctx.fillRect(s.x,s.y,s.z,s.z*2)}
if(G.player){const p=G.player;ctx.save();ctx.translate(p.x,p.y);ctx.shadowBlur=14;ctx.shadowColor='#6ef';ctx.fillStyle=['#ff7d7d','#9fe8ff','#d0a6ff'][G.ship];ctx.beginPath();ctx.moveTo(0,-24);ctx.lineTo(16,8);ctx.lineTo(10,20);ctx.lineTo(0,12);ctx.lineTo(-10,20);ctx.lineTo(-16,8);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(-2,-2,4,4);ctx.restore();}
for(const e of G.en){ctx.fillStyle=['#f35','#fa0','#f66','#8af','#c6f','#fb8'][e.k];ctx.beginPath();ctx.moveTo(e.x,e.y-10);ctx.lineTo(e.x+12,e.y);ctx.lineTo(e.x,e.y+10);ctx.lineTo(e.x-12,e.y);ctx.closePath();ctx.fill();}
if(G.boss){ctx.fillStyle=G.boss.ph===3?'#f3f':G.boss.ph===2?'#f94':'#f55';ctx.beginPath();ctx.rect(G.boss.x-72,G.boss.y-38,144,76);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(G.boss.x-6,G.boss.y-6,12,12);if(G.boss.warn>0){ctx.fillStyle=`rgba(255,0,0,${Math.sin(G.boss.warn*.35)*.2+.2})`;ctx.fillRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#fff';ctx.font='bold 42px sans-serif';ctx.fillText('WARNING',innerWidth/2-108,innerHeight/2);ctx.font='16px sans-serif';ctx.fillText(G.boss.name,innerWidth/2-56,innerHeight/2+22);}}
for(const b of G.bul){ctx.shadowBlur=10;ctx.shadowColor=b.c;ctx.fillStyle=b.c;ctx.fillRect(b.x-2,b.y-7,4,12)}for(const b of G.eb){ctx.shadowBlur=8;ctx.shadowColor=b.c;ctx.fillStyle=b.c;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,6.28);ctx.fill()}
}
function sync(){if(!G.player)return;score.textContent=Math.floor(G.score);stageNo.textContent=G.stage;shipName.textContent=ships[G.ship].name.split(' ')[0];wpn.textContent=['VULCAN','SPREAD','LASER'][G.wpn];life.textContent=G.life;hp.textContent=Math.max(0,Math.floor(G.player.hp));shield.textContent=Math.max(0,Math.floor(G.player.sh));skill.textContent=Math.floor(G.player.sk);bomb.textContent=G.bomb;}
function loop(ts){try{if(!G.last)G.last=ts;let dt=Math.min(.033,(ts-G.last)/1000);G.last=ts;update(dt);draw();requestAnimationFrame(loop);}catch(e){console.error(e);show('menu');requestAnimationFrame(loop);}}
addEventListener('pointerdown',e=>{if(e.target.closest('.btn'))return;if(G.scene==='game'&&G.player){G.input.id=e.pointerId;G.input.sx=e.clientX;G.input.sy=e.clientY;G.input.px=G.player.x;G.input.py=G.player.y;G.input.drag=true;}},{passive:false});
addEventListener('pointermove',e=>{if(!G.input.drag||e.pointerId!==G.input.id||!G.player)return;const dx=e.clientX-G.input.sx,dy=e.clientY-G.input.sy;G.player.x=clamp(G.input.px+dx*set.sens,G.player.r,innerWidth-G.player.r);G.player.y=clamp(G.input.py+dy*set.sens,G.player.r,innerHeight-G.player.r);},{passive:false});
for(const ev of ['pointerup','pointercancel'])addEventListener(ev,e=>{if(e.pointerId===G.input.id){G.input.drag=false;G.input.id=null;}},{passive:false});
bootUI();requestAnimationFrame(loop);
