window.__LT2_BOOT_OK__=true;
const q=id=>document.getElementById(id); const scenes=['title','mainMenu','hangar','settings','how','credits','result'];
const S={scene:'boot',running:false,paused:false,score:0,stage:1,ship:0,wpn:0,life:3,bomb:3,time:0,player:null,en:[],eb:[],pb:[],boss:null,last:0,input:{id:null,sx:0,sy:0,px:0,py:0,drag:false,sens:1.1},settings:{difficulty:'Normal',shake:true,flash:true,hitbox:false,quality:'Medium',vol:.6}};
const SHIPS=[{name:'CRIMSON FALCON',role:'Balanced'},{name:'NOVA SPEAR',role:'Wide'},{name:'ECLIPSE RAY',role:'Laser'}];
const cv=q('game'),ctx=cv.getContext('2d');
function err(e){console.error(e);q('err').style.display='block';q('err').textContent=String(e.stack||e)}
function showScene(id){scenes.forEach(s=>q(s).classList.remove('show'));q('hud').classList.remove('show');if(id){q(id).classList.add('show');S.scene=id;}else{q('hud').classList.add('show');S.scene='gameplay';}}
function resize(){const d=Math.min(2,devicePixelRatio||1);cv.width=innerWidth*d;cv.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0);}addEventListener('resize',resize);resize();
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function bindStart(el){['pointerdown','touchstart','click'].forEach(ev=>el.addEventListener(ev,e=>{e.preventDefault();if(S.scene==='title')showScene('mainMenu');},{passive:false}));}
function loadSettings(){try{Object.assign(S.settings,JSON.parse(localStorage.getItem('aegis_settings')||'{}'));}catch{}}
function persistSettings(){localStorage.setItem('aegis_settings',JSON.stringify(S.settings));}
function startGame(){S.running=true;S.paused=false;S.score=0;S.time=0;S.life=3;S.bomb=3;S.wpn=0;S.en=[];S.eb=[];S.pb=[];S.boss=null;S.player={x:innerWidth/2,y:innerHeight*.82,hp:100,sh:60,sk:0,r:10,cd:0};showScene(null);spawnWave();syncHUD();}
function spawnWave(){if(S.stage%4===0){const n=(S.stage%8===0)?'HELIOS CORE':'IRON MAW';S.boss={name:n,hp:1600,max:1600,ph:1,x:innerWidth/2,y:110,cd:20,warn:120};q('bossName').textContent=n;q('bossBarWrap').style.display='block';return;}q('bossBarWrap').style.display='none';for(let i=0;i<8+S.stage;i++)S.en.push({t:i%6,x:60+(i*77)%Math.max(innerWidth-120,120),y:-40-i*55,hp:30+(i%3)*35,a:Math.random()*6.28,cd:40});}
function syncHUD(){if(!S.player)return;score.textContent=Math.floor(S.score);stage.textContent=S.stage;ship.textContent=SHIPS[S.ship].name.split(' ')[0];wpn.textContent=['VULCAN','SPREAD','LASER'][S.wpn];life.textContent=S.life;bomb.textContent=S.bomb;hp.textContent=Math.floor(S.player.hp);sh.textContent=Math.floor(S.player.sh);sk.textContent=Math.floor(S.player.sk);if(S.boss)bossBar.style.width=(S.boss.hp/S.boss.max*100)+'%';}
function fire(dt){const p=S.player;p.cd-=dt*60;if(p.cd>0)return;p.cd=S.wpn===0?4:S.wpn===1?7:9;if(S.wpn===0)[-1,0,1].forEach(v=>S.pb.push({x:p.x+v*4,y:p.y-18,vx:v*.6,vy:-13,d:8,c:'#7ef'}));if(S.wpn===1)[-3,-1,1,3].forEach(v=>S.pb.push({x:p.x,y:p.y-16,vx:v,vy:-10,d:7,c:'#9f8'}));if(S.wpn===2)[-7,7].forEach(v=>S.pb.push({x:p.x+v,y:p.y-14,vx:0,vy:-18,d:16,c:'#f8f'}));}
function skill(){if(!S.player||S.player.sk<100)return;S.player.sk=0;for(let i=0;i<40;i++){const a=i/40*Math.PI*2;S.pb.push({x:S.player.x,y:S.player.y,vx:Math.cos(a)*6,vy:Math.sin(a)*6,d:12,c:'#fff'});} }
function bombUse(){if(S.bomb<=0)return;S.bomb--;S.eb=[];S.en.forEach(e=>e.hp-=140);if(S.boss)S.boss.hp-=220;}
function update(dt){if(!S.running||S.paused||S.scene!=='gameplay')return;S.time+=dt;const p=S.player;fire(dt);p.sk=clamp(p.sk+dt*4,0,100);
for(const e of S.en){e.y+=1.6+(e.t===2?1.2:0);e.a+=dt*2;if(e.t===0)e.x+=Math.sin(e.a)*2.2;if(e.t===1)e.x+=Math.cos(e.a)*2.7;e.cd-=dt*60;if(e.cd<0){e.cd=e.t===4?22:52;S.eb.push({x:e.x,y:e.y,vx:(Math.random()*2-1)*(e.t===5?2.4:1.2),vy:3.2,r:4,c:['#2ff','#fb0','#f66','#8af','#c8f','#fe8'][e.t]});}}
if(S.boss){const b=S.boss;b.warn=Math.max(0,b.warn-dt*60);b.ph=b.hp<b.max*.33?3:b.hp<b.max*.66?2:1;b.x=innerWidth/2+Math.sin(S.time)*180;b.cd-=dt*60;if(b.warn===0&&b.cd<0){if(b.ph===1){b.cd=14;for(let i=0;i<16;i++){let a=i/16*Math.PI*2+S.time;S.eb.push({x:b.x,y:b.y,vx:Math.cos(a)*2.2,vy:Math.sin(a)*2.2+1.2,r:4,c:'#f77'});}}if(b.ph===2){b.cd=10;let dx=p.x-b.x,dy=p.y-b.y,d=Math.hypot(dx,dy)||1;S.eb.push({x:b.x,y:b.y,vx:dx/d*4.4,vy:dy/d*4.4,r:5,c:'#fd6'});}if(b.ph===3){b.cd=8;for(let k=-2;k<=2;k++)S.eb.push({x:b.x+k*24,y:b.y,vx:0,vy:5.6,r:5,c:'#0ef'});}}}
S.pb.forEach(b=>{b.x+=b.vx*dt*60;b.y+=b.vy*dt*60});S.eb.forEach(b=>{b.x+=b.vx*dt*60;b.y+=b.vy*dt*60});
for(const b of S.pb){for(const e of S.en){if((b.x-e.x)**2+(b.y-e.y)**2<260){b.h=1;e.hp-=b.d;if(e.hp<=0){e.d=1;S.score+=100;p.sk=clamp(p.sk+5,0,100);}}}if(S.boss&&((b.x-S.boss.x)**2+(b.y-S.boss.y)**2<5600)){b.h=1;S.boss.hp-=b.d;}}
for(const b of S.eb){const d2=(b.x-p.x)**2+(b.y-p.y)**2;if(d2<250){b.h=1;if(p.sh>0)p.sh=Math.max(0,p.sh-10);else p.hp-=10;}else if(d2<1200)p.sk=clamp(p.sk+dt*10,0,100)}
if(p.hp<=0){S.life--;if(S.life<0)return endGame(false);p.hp=100;p.sh=60;p.x=innerWidth/2;p.y=innerHeight*.82;}
S.en=S.en.filter(e=>!e.d&&e.y<innerHeight+80);S.pb=S.pb.filter(b=>!b.h&&b.y>-30);S.eb=S.eb.filter(b=>!b.h&&b.y<innerHeight+20&&b.x>-20&&b.x<innerWidth+20);
if(S.boss&&S.boss.hp<=0){S.score+=5000;S.boss=null;S.stage++;if(S.stage>4)return endGame(true);spawnWave();}
if(!S.boss&&S.en.length===0){S.stage++;spawnWave();}
syncHUD();}
function endGame(clear){S.running=false;showScene('result');resultTitle.textContent=clear?'MISSION CLEAR':'GAME OVER';resultBody.textContent=`Score ${Math.floor(S.score)} / Time ${S.time.toFixed(1)}s`;}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=['#2ff','#fa0','#f66','#9af','#d7f','#fe8'][e.t];ctx.shadowBlur=10;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();if(e.t===0){ctx.moveTo(0,-10);ctx.lineTo(10,8);ctx.lineTo(-10,8);}if(e.t===1){ctx.moveTo(0,-12);ctx.lineTo(12,0);ctx.lineTo(0,12);ctx.lineTo(-12,0);}if(e.t===2){ctx.rect(-14,-8,28,16);}if(e.t===3){ctx.moveTo(-12,-8);ctx.lineTo(12,-4);ctx.lineTo(10,8);ctx.lineTo(-10,10);}if(e.t===4){ctx.moveTo(0,-14);ctx.lineTo(14,0);ctx.lineTo(0,14);ctx.lineTo(-14,0);}if(e.t===5){ctx.rect(-10,-10,20,20);ctx.moveTo(-14,0);ctx.lineTo(14,0);}ctx.closePath();ctx.fill();ctx.restore();}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);const bg=ctx.createLinearGradient(0,0,0,innerHeight);bg.addColorStop(0,'#071629');bg.addColorStop(0.5,'#102a4e');bg.addColorStop(1,'#050b16');ctx.fillStyle=bg;ctx.fillRect(0,0,innerWidth,innerHeight);for(let i=0;i<60;i++){ctx.fillStyle='rgba(150,220,255,.25)';ctx.fillRect((i*73+S.time*50)%innerWidth,(i*131+S.time*120)%innerHeight,2,3);}if(S.player){ctx.save();ctx.translate(S.player.x,S.player.y);ctx.fillStyle=['#ff7b7b','#8fe9ff','#d8a5ff'][S.ship];ctx.shadowBlur=16;ctx.shadowColor=ctx.fillStyle;ctx.beginPath();ctx.moveTo(0,-24);ctx.lineTo(16,8);ctx.lineTo(9,20);ctx.lineTo(0,12);ctx.lineTo(-9,20);ctx.lineTo(-16,8);ctx.closePath();ctx.fill();if(S.settings.hitbox){ctx.fillStyle='#fff';ctx.fillRect(-1,-1,2,2);}ctx.restore();}
S.en.forEach(drawEnemy);if(S.boss){ctx.fillStyle=S.boss.ph===3?'#f3f':S.boss.ph===2?'#f94':'#f55';ctx.fillRect(S.boss.x-70,S.boss.y-38,140,76);ctx.fillStyle='#fff';ctx.fillRect(S.boss.x-5,S.boss.y-5,10,10);if(S.boss.warn>0){ctx.fillStyle='rgba(255,0,0,.25)';ctx.fillRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#fff';ctx.font='bold 44px sans-serif';ctx.fillText('WARNING',innerWidth/2-110,innerHeight/2);ctx.font='16px sans-serif';ctx.fillText(S.boss.name,innerWidth/2-45,innerHeight/2+24);}}
S.pb.forEach(b=>{ctx.fillStyle=b.c;ctx.shadowBlur=10;ctx.shadowColor=b.c;ctx.fillRect(b.x-2,b.y-7,4,12)});S.eb.forEach(b=>{ctx.fillStyle=b.c;ctx.strokeStyle='#001';ctx.lineWidth=1;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,6.28);ctx.fill();ctx.stroke();});}
function loop(ts){try{if(!S.last)S.last=ts;const dt=Math.min(.033,(ts-S.last)/1000);S.last=ts;update(dt);draw();requestAnimationFrame(loop);}catch(e){err(e);requestAnimationFrame(loop);}}
function bindUI(){bindStart(q('titleStart'));bindStart(q('titleTap'));q('title').addEventListener('pointerdown',()=>{if(S.scene==='title')showScene('mainMenu')});
q('startMission').onclick=()=>startGame();q('openHangar').onclick=()=>showScene('hangar');q('openSettings').onclick=()=>showScene('settings');q('openHow').onclick=()=>showScene('how');q('openCredits').onclick=()=>showScene('credits');
q('hangarBack').onclick=()=>showScene('mainMenu');q('settingsBack').onclick=()=>showScene('mainMenu');q('howBack').onclick=()=>showScene('mainMenu');q('creditsBack').onclick=()=>showScene('mainMenu');q('resultBack').onclick=()=>showScene('mainMenu');
shipCards.innerHTML=SHIPS.map((s,i)=>`<button class='btn' data-ui='true' data-s='${i}'>${s.name} / ${s.role}</button>`).join('');shipCards.onclick=e=>{if(e.target.dataset.s)S.ship=+e.target.dataset.s};
q('saveSettings').onclick=()=>{Object.assign(S.settings,{difficulty:difficulty.value,sens:+sens.value,shake:shake.checked,flash:flash.checked,hitbox:hitbox.checked,quality:quality.value,vol:+vol.value});S.input.sens=S.settings.sens;persistSettings();showScene('mainMenu');};
q('resetSave').onclick=()=>{localStorage.removeItem('aegis_settings');location.reload();};q('pauseBtn').onclick=()=>S.paused=!S.paused;q('wpnBtn').onclick=()=>S.wpn=(S.wpn+1)%3;q('skillBtn').onclick=()=>skill();q('bombBtn').onclick=()=>bombUse();
}
function saveSettingsData(){localStorage.setItem('aegis_settings',JSON.stringify(S.settings));}
function init(){if(!cv)throw new Error('canvas not found');loadSettings();sens.value=S.settings.sens;q('shake').checked=S.settings.shake;q('flash').checked=S.settings.flash;q('hitbox').checked=S.settings.hitbox;q('quality').value=S.settings.quality;q('vol').value=S.settings.vol;S.input.sens=S.settings.sens;bindUI();showScene('title');}
addEventListener('pointerdown',e=>{if(S.scene!=='gameplay'||!S.running)return;if(e.target.closest('[data-ui="true"]'))return;S.input.id=e.pointerId;S.input.sx=e.clientX;S.input.sy=e.clientY;S.input.px=S.player.x;S.input.py=S.player.y;S.input.drag=true;},{passive:false});
addEventListener('pointermove',e=>{if(!S.input.drag||e.pointerId!==S.input.id||!S.player)return;const dx=e.clientX-S.input.sx,dy=e.clientY-S.input.sy;const nx=S.input.px+dx*S.input.sens,ny=S.input.py+dy*S.input.sens;if(Number.isFinite(nx)&&Number.isFinite(ny)){S.player.x=clamp(nx,S.player.r,innerWidth-S.player.r);S.player.y=clamp(ny,S.player.r,innerHeight-S.player.r);}},{passive:false});
['pointerup','pointercancel'].forEach(ev=>addEventListener(ev,e=>{if(e.pointerId===S.input.id){S.input.drag=false;S.input.id=null;}},{passive:false}));
try{init();requestAnimationFrame(loop);}catch(e){err(e)}
